# fly.toml app configuration file generated for run-yo8ntw on 2026-06-20T09:34:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'run-yo8ntw'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
