# fly.toml app configuration file generated for run-ybnjiq on 2026-06-19T19:47:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'run-ybnjiq'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false   # keep bot running 24/7
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "512mb"             # bump to 1gb if bot needs more
  cpu_kind = "shared"
  cpus = 1
